spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oboshie-fashion
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: root
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000