server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oboshie-fashion
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: root
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  name: Oboshie Fasion💃
  mail:
    confirmation:
      from: confirmation@oboshie-fasion.com
      subject: Confirm your email
  url:
    base: http://localhost:8080/
    registration: api/v1/registration/
    token.confirmation: confirm?token=

api-docs.path: /v3/api-docs
# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled: false
# Disabling the swagger-ui
springdoc.swagger-ui.enabled: false