server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oboshie-fashion
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: root
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  banner:
    location: classpath:/banner-${spring.profile.active}.txt
  profile:
    active: default

app:
  name: Oboshie Fasion💃
  description: A web API for ${app.name}
  mail:
    from: confirmation@oboshie-fasion.com
    unlock:
      subject:  "${app.name}: Unlock your Account"
      message: Your request has been received.\nTo ensure that you triggered this request, your account has been locked.\nPlease click on the below link to unlock your account
    confirm:
      subject: "${app.name}: Confirm your email"
      message: Thank you for registering. Please click on the below link to activate your account
  url:
    base: "http://localhost:8080/"
    confirm: ${app.url.base}user/confirm?token=
    unlock: ${app.url.base}user/unlock?token=

jwt:
  secret: "secret"

api-docs.path: /v3/api-docs
# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled: true
# Disabling the swagger-ui
springdoc.swagger-ui.enabled: true

my:
  greeting: hello world from internal resource!